name: PR Changes

on:
  pull_request:
   
jobs:
  build:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.13.9'
      - run: dart pub global activate arb_utils
      - run: flutter pub get
      - run: flutter clean 
      - run: make gen
      - run: make l10n
      - run: make tests-ci-cd

